# Generated by Django 5.2.6 on 2025-09-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_registrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('event_title', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('registered_count', models.IntegerField()),
                ('occupancy_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'event_occupancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_registrations', models.IntegerField()),
            ],
            options={
                'db_table': 'monthly_registrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('event_title', models.CharField(max_length=255)),
                ('total_attendance', models.IntegerField()),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'sessions_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotificationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('unread_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user_notification_stats',
                'managed': False,
            },
        ),
    ]
