# Generated by Django 4.2.7 on 2025-09-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='booksale',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='goodiesale',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='user',
        ),
    ]
